### PR TITLE
fix(login button): in header login button import error solve

### LINKED ISSUE #22: Fix/login button import error

### PR DESCRIPTION
**Pull request by mimshifat**

### CODE REVIEW

File: app/components/ui/Header.jsx [hunk 1]
```diff
@@ -1,7 +1,10 @@
-import LoginRegButton from "./LoginRegButton";
+// import LoginRegButton from "./LoginRegButton";
+
+import LoginRegButton from "./loginRegButton";
 
 export default function Header() {
     return (
-        <LoginRegButton />
+        // <LoginRegButton />
+        <LoginRegButton/>
```
Comment (MD-Mehedi-Hasan-Talha) [inline app/components/ui/Header.jsx:8]: Please explain me what you have done in this PR or issue?

Comment (mimshifat) [reply app/components/ui/Header.jsx:8]: first show this line // import LoginRegButton from "./LoginRegButton";
but this line show error

after this line fix the import error import LoginRegButton from "./loginRegButton";

different L and l

Comment (MD-Mehedi-Hasan-Talha) [reply app/components/ui/Header.jsx:8]: Oh, sorry, I haven't saw it. ok. it will be merged
